apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: python-consumer
  name: python-consumer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: python-consumer
    spec:
      containers:
      - image: python-consumer
        name: python-consumer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
